version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www
            - ./storage:/var/www/storage
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=smk_paskita
            - DB_USERNAME=root
            - DB_PASSWORD=oppungmarajomba

    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: oppungmarajomba
            MYSQL_DATABASE: smk_paskita
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
